2do año/ENTORNO SERVIDOR/Supuesto Integrador/Tienda/TiendaPadel/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TiendaPadel.Data;
using TiendaPadel.Models;

namespace TiendaPadel.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ClientesController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public ClientesController(MvcTiendaContexto context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index(int? pageNumber, string? strCadenaBusqueda, string? strCadenaEmail, string? strCadenaPoblacion)
        {
            ViewData["BusquedaActual"] = strCadenaBusqueda;
            ViewData["BusquedaEmail"] = strCadenaEmail;
            ViewData["BusquedaPoblacion"] = strCadenaPoblacion;

            // Cargar datos de Pedidos
            var clientes = from s in _context.Clientes
                          select s;

            if (!String.IsNullOrEmpty(strCadenaBusqueda))
            {
                clientes = clientes.Where(s => s.Nif.Contains(strCadenaBusqueda));
            }

            if (!String.IsNullOrEmpty(strCadenaEmail))
            {
                clientes = clientes.Where(s => s.Email.Contains(strCadenaEmail));
            }

            if (!String.IsNullOrEmpty(strCadenaPoblacion))
            {
                clientes = clientes.Where(s => s.Poblacion.Contains(strCadenaPoblacion));
            }


            int pageSize = 8;
            return View(await PaginatedList<Cliente>.CreateAsync(clientes.AsNoTracking(),
            pageNumber ?? 1, pageSize));
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);


        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Nif,Email,Telefono,Direccion,Poblacion,CodigoPostal")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Nif,Email,Telefono,Direccion,Poblacion,CodigoPostal")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

2do año/ENTORNO SERVIDOR/Supuesto Integrador/Tienda/TiendaPadel/Controllers/EstadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TiendaPadel.Data;
using TiendaPadel.Models;

namespace TiendaPadel.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class EstadosController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public EstadosController(MvcTiendaContexto context)
        {
            _context = context;
        }

        // GET: Estados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estados.ToListAsync());
        }

        // GET: Estados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // GET: Estados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados.FindAsync(id);
            if (estado == null)
            {
                return NotFound();
            }
            return View(estado);
        }

        // POST: Estados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion")] Estado estado)
        {
            if (id != estado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoExists(estado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estado);
        }

        // GET: Estados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estado = await _context.Estados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estado == null)
            {
                return NotFound();
            }

            return View(estado);
        }

        // POST: Estados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estado = await _context.Estados.FindAsync(id);
            if (estado != null)
            {
                _context.Estados.Remove(estado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoExists(int id)
        {
            return _context.Estados.Any(e => e.Id == id);
        }
    }
}

2do año/ENTORNO SERVIDOR/Supuesto Integrador/Tienda/TiendaPadel/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TiendaPadel.Data;
using TiendaPadel.Models;

namespace TiendaPadel.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PedidosController : Controller
    {
        private readonly MvcTiendaContexto _context;

        public PedidosController(MvcTiendaContexto context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index(int? pageNumber, DateTime? fecha, string? strCadenaUsuario, string? strCadenaEstado)
        {
            ViewData["BusquedaFecha"] = fecha.HasValue ? fecha.Value.ToString("yyyy-MM-dd") : "";
            ViewData["BusquedaUsuario"] = strCadenaUsuario;
            ViewData["BusquedaEstado"] = strCadenaEstado;

            // Cargar datos de Pedidos e incluir Detalles, Productos e Imagenes
            var pedidos = _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.Estado)
                .Include(p => p.Detalles)
                    .ThenInclude(d => d.Producto) // Incluir el producto dentro del detalle
                        .ThenInclude(prod => prod.Imagenes) // Incluir las imágenes del producto
                .OrderByDescending(p => p.Id)
                .AsQueryable();

            // Filtrar por fecha si se proporciona
            if (fecha.HasValue)
            {
                pedidos = pedidos.Where(s => s.Fecha.Date == fecha.Value.Date);
            }

            // Filtrar por usuario
            if (!string.IsNullOrEmpty(strCadenaUsuario))
            {
                pedidos = pedidos.Where(s => s.Cliente.Nombre == strCadenaUsuario);
            }

            // Filtrar por estado
            if (!string.IsNullOrEmpty(strCadenaEstado))
            {
                switch (strCadenaEstado)
                {
                    case "Pendiente":
                        pedidos = pedidos.Where(s => s.Estado.Descripcion == "Pendiente");
                        break;
                    case "Realizado":
                        pedidos = pedidos.Where(s => s.Estado.Descripcion == "Realizado");
                        break;
                }
            }



            int pageSize = 8;
            return View(await PaginatedList<Pedido>.CreateAsync(pedidos.AsNoTracking(),
            pageNumber ?? 1, pageSize));
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }



            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.Estado)
                .Include(p => p.Detalles)
                    .ThenInclude(d => d.Producto)
                        .ThenInclude(prod => prod.Imagenes) // 🔹 Incluye las imágenes correctamente
                .FirstOrDefaultAsync(p => p.Id == id);

            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre");
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Descripcion");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Confirmado,Preparado,Enviado,Cobrado,Devuelto,Anulado,ClienteId,EstadoId")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Descripcion", pedido.EstadoId);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Descripcion", pedido.EstadoId);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Confirmado,Preparado,Enviado,Cobrado,Devuelto,Anulado,ClienteId,EstadoId")] Pedido pedido)
        {
            if (id != pedido.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedido.ClienteId);
            ViewData["EstadoId"] = new SelectList(_context.Estados, "Id", "Descripcion", pedido.EstadoId);
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.Estado)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);

            if (pedido != null)
            {
                pedido.Anulado = DateTime.Now;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.Id == id);
        }
    }
}

2do año/ENTORNO SERVIDOR/Supuesto Integrador/Tienda/TiendaPadel/Views/Shared/_Layout.cshtml
@{
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
    var hideNavFooter = (currentController == "Carrito" && currentAction == "Index");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        .card {
            height: 500px; /* Establece una altura fija para todas las cards */
        }

        .card-img-top {
            height: 350px; /* Establece una altura fija para la imagen */
            object-fit: cover; /* Hace que la imagen se recorte proporcionalmente para llenar el contenedor */
        }

        .card-body {
            height: calc(100% - 200px); /* Ajusta la altura del cuerpo de la card (restando la altura de la imagen) */
        }

        #loading-screen{
            position: fixed;
            width: 100%;
            height: 100%;
            background: rgb(255,255,255);
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 24px;
            z-index: 9999;
        }

        #page-content {
            display: none;
        }
    </style>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TiendaPadel</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chonburi&family=Playfair:ital,opsz,wdth,wght@1,5..1200,87.5,300&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/onload.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/TiendaPadel.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>
    <header id="page-content" style="@(hideNavFooter ? "display: none;" : "")">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom border-nav">
            <div class="container-fluid">
                @if (User.IsInRole("Administrador"))
                {
                    <!-- Logo a la izquierda para administradores -->
                    <a class="me-auto" asp-area="" asp-controller="Home" asp-action="Index">
                        <h1 class="fuente-logo color-terciario fs-1 fw-bold" style="font-size: 2em;margin-right: 20px;">XPADEL</h1>
                    </a>
                }
                else
                {
                    <!-- Logo centrado para otros usuarios -->
                    <a class="navbar-brand mx-auto" asp-area="" asp-controller="Home" asp-action="Index">
                        <h1 class="fuente-logo color-terciario fs-1 fw-bold">XPADEL</h1>
                    </a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Usuario"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link color-terciario fuente-editorial  text-center" asp-area="" asp-controller="Escaparate" asp-action="Index">SHOP</a>
                                </li>
                                

                                <li class="nav-item">
                                    <a class="nav-link color-terciario fuente-editorial text-center" asp-controller="Home" asp-action="Index" asp-fragment="NEW">NEW</a>
                                </li>
                                 <li class="nav-item">
                                    <a class="nav-link color-terciario fuente-editorial text-center" asp-area="" asp-controller="Home" asp-action="Privacy">PRIVACIDAD</a>
                                    </li>
                            }
                            @if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Categorias" asp-action="Index">
                                        <i class="bi bi-inboxes"></i> 
                                         Categorias
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Productos" asp-action="Index"><i class="bi bi-box-seam"></i> Productos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Pedidos" asp-action="Index"><i class="bi bi-mailbox-flag"></i> Pedidos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Clientes" asp-action="Index"><i class="bi bi-people"></i> Clientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Estados" asp-action="Index"><i class="bi bi-truck"></i> Estados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-center" asp-area="" asp-controller="Usuarios" asp-action="Index"><i class="bi bi-person-gear"></i> Usuarios</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link color-terciario fuente-editorial text-center" asp-area="" asp-controller="Escaparate" asp-action="Index">SHOP</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link color-terciario fuente-editorial text-center" asp-controller="Home" asp-action="Index" asp-fragment="NEW">NEW</a>
                            </li>
                        }
                    </ul>
                    
                    <div class="navbar-nav ms-auto">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div id="loading-screen">
        <h1 class="fuente-logo color-terciario typewriter">XPADEL...</h1>
    </div>
    
    <div id="page-content" class="d-flex flex-column min-vh-100">
        <div class="container flex-grow-1">
            <main role="main">
                @RenderBody()
            </main>
        </div>

        <div class="border-top text-center" style="@(hideNavFooter ? "display: none;" : "")">
            <!-- Section: Social media -->
            <section class="d-flex justify-content-center justify-content-lg-between p-1 border-bottom">
                <div class="justify-content-between w-100">
                    <a href="https://x.com/?lang=es" class="me-4 text-reset color-principal">
                        <i class="bi bi-twitter-x"></i>
                    </a>
                    <a href="#Escaparate" class="me-4 text-reset color-principal">
                        <i class="bi bi-google"></i>
                    </a>
                    <a href="#Escaparate" class="me-4 text-reset color-principal">
                        <i class="bi bi-instagram"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/leo-coves-guzman-b68554281/" class="me-4 text-reset color-principal">
                        <i class="bi bi-linkedin"></i>
                    </a>
                    <a href="https://github.com/LeoCoves/" class="me-4 text-reset color-principal">
                        <i class="bi bi-github"></i>
                    </a>
                </div>
                <!-- Right -->
            </section>
            <section class="">
                <div class="container text-center text-md-start mt-4">
                    <!-- Grid row -->
                    <div class="row mt-2">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-2">
                            <!-- Content -->
                            <h6 class="text-uppercase fw-bold mb-2">
                                Nombre de la compañia
                            </h6>
                            <a class="me-auto" asp-area="" asp-controller="Home" asp-action="Index">
                                <h1 class="fuente-logo color-terciario fs-1 fw-bold">XPADEL</h1>
                            </a>
                        </div>
                        <!-- Grid column -->
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-2">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-2">
                                Productos
                            </h6>
                            <p>
                                <a href="#Escaparate" class="text-reset">Palas</a>
                            </p>
                            <p>
                                <a href="#Escaparate" class="text-reset">Accesorios</a>
                            </p>
                            <p>
                                <a href="#Escaparate" class="text-reset">Pelotas</a>
                            </p>
                            <p>
                                <a href="#Escaparate" class="text-reset">Mas</a>
                            </p>
                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2">

                            <h6 class="text-uppercase fw-bold mb-2">
                                Tecnologias
                            </h6>
                            <p>
                                <a href="https://dotnet.microsoft.com/es-es/languages/csharp" class="text-reset">C#</a>
                            </p>
                            <p>
                                <a href="https://dotnet.microsoft.com/es-es/" class="text-reset">.NET</a>
                            </p>
                            <p>
                                <a href="https://dotnet.microsoft.com/es-es/apps/aspnet/mvc" class="text-reset">MVC</a>
                            </p>
                            <p>
                                <a href="https://getbootstrap.com/" class="text-reset">Boostrap</a>
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-2">
                            <h6 class="text-uppercase fw-bold mb-2">Contactanos</h6>
                            <p><i class="bi bi-backpack"></i> IES Mare Nostrum, ES</p>
                            <p>
                                <i class="bi bi-envelope-at-fill"></i>
                                leocovguz@alu.edu.gva.es
                            </p>
                            <p><i class="bi bi-telephone-fill"></i> 48847487847</p>
                            <p><i class="bi bi-telephone-fill"></i> 34834758748</p>
                        </div>
                    </div>
                </div>
            </section>
            <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.05);">
                © 2021 Copyright:
                <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
            </div>
            <!-- Copyright -->
        </div>
    </div>

    <div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasCarrito" aria-labelledby="offcanvasCarritoLabel">
        <div class="offcanvas-header">
            <h5 id="offcanvasCarritoLabel"><i class="bi bi-cart"></i></h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
        </div>
        <div class="offcanvas-body" id="contenidoCarrito">
            Cargando...
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    

    <script src="~/js/onload.js"></script>
    <script src="~/js/verCarrito.js"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>